In [1]:
# 基础组件Model

## 模型微调代码实例 
### 任务类型
#### 文本分类

## 使用模型
### hfl/rbt3

## 数据集地址

In [5]:
# 文本分类

## step1 导包
from transformers import AutoTokenizer,AutoModelForSequenceClassification

In [6]:
# 加载数据
import pandas as pd

data = pd.read_csv("./ChnSentiCorp_htl_all.csv")
data.head()
data

      label                                             review
0         1  距离川沙公路较近,但是公交指示不对,如果是"蔡陆线"的话,会非常麻烦.建议用别的路线.房间较...
1         1                       商务大床房，房间很大，床有2M宽，整体感觉经济实惠不错!
2         1         早餐太差，无论去多少人，那边也不加食品的。酒店应该重视一下这个问题了。房间本身很好。
3         1  宾馆在小街道上，不大好找，但还好北京热心同胞很多~宾馆设施跟介绍的差不多，房间很小，确实挺小...
4         1               CBD中心,周围没什么店铺,说5星有点勉强.不知道为什么卫生间没有电吹风
...     ...                                                ...
7761      0  尼斯酒店的几大特点：噪音大、环境差、配置低、服务效率低。如：1、隔壁歌厅的声音闹至午夜3点许...
7762      0  盐城来了很多次，第一次住盐阜宾馆，我的确很失望整个墙壁黑咕隆咚的，好像被烟熏过一样家具非常的...
7763      0  看照片觉得还挺不错的，又是4星级的，但入住以后除了后悔没有别的，房间挺大但空空的，早餐是有但...
7764      0  我们去盐城的时候那里的最低气温只有4度，晚上冷得要死，居然还不开空调，投诉到酒店客房部，得到...
7765      0  说实在的我很失望，之前看了其他人的点评后觉得还可以才去的，结果让我们大跌眼镜。我想这家酒店以...

[7766 rows x 2 columns]

In [7]:
# 删除空数据
data = data.dropna()
data

      label                                             review
0         1  距离川沙公路较近,但是公交指示不对,如果是"蔡陆线"的话,会非常麻烦.建议用别的路线.房间较...
1         1                       商务大床房，房间很大，床有2M宽，整体感觉经济实惠不错!
2         1         早餐太差，无论去多少人，那边也不加食品的。酒店应该重视一下这个问题了。房间本身很好。
3         1  宾馆在小街道上，不大好找，但还好北京热心同胞很多~宾馆设施跟介绍的差不多，房间很小，确实挺小...
4         1               CBD中心,周围没什么店铺,说5星有点勉强.不知道为什么卫生间没有电吹风
...     ...                                                ...
7761      0  尼斯酒店的几大特点：噪音大、环境差、配置低、服务效率低。如：1、隔壁歌厅的声音闹至午夜3点许...
7762      0  盐城来了很多次，第一次住盐阜宾馆，我的确很失望整个墙壁黑咕隆咚的，好像被烟熏过一样家具非常的...
7763      0  看照片觉得还挺不错的，又是4星级的，但入住以后除了后悔没有别的，房间挺大但空空的，早餐是有但...
7764      0  我们去盐城的时候那里的最低气温只有4度，晚上冷得要死，居然还不开空调，投诉到酒店客房部，得到...
7765      0  说实在的我很失望，之前看了其他人的点评后觉得还可以才去的，结果让我们大跌眼镜。我想这家酒店以...

[7765 rows x 2 columns]

In [8]:
## 创建DataSet
from torch.utils.data import Dataset

class MyDataSet(Dataset):

    def __init__(self) -> None:
        super().__init__()
        self.data = pd.read_csv("./ChnSentiCorp_htl_all.csv")
        self.data = self.data.dropna()

    def __getitem__(self, index):
        return self.data.iloc[index]["review"],  self.data.iloc[index]["label"]
    
    def __len__(self):
        return len(self.data)

In [9]:
dataset = MyDataSet()
for i in range(5):
    print(dataset[i])

('距离川沙公路较近,但是公交指示不对,如果是"蔡陆线"的话,会非常麻烦.建议用别的路线.房间较为简单.', 1)
('商务大床房，房间很大，床有2M宽，整体感觉经济实惠不错!', 1)
('早餐太差，无论去多少人，那边也不加食品的。酒店应该重视一下这个问题了。房间本身很好。', 1)
('宾馆在小街道上，不大好找，但还好北京热心同胞很多~宾馆设施跟介绍的差不多，房间很小，确实挺小，但加上低价位因素，还是无超所值的；环境不错，就在小胡同内，安静整洁，暖气好足-_-||。。。呵还有一大优势就是从宾馆出发，步行不到十分钟就可以到梅兰芳故居等等，京味小胡同，北海距离好近呢。总之，不错。推荐给节约消费的自助游朋友~比较划算，附近特色小吃很多~', 1)
('CBD中心,周围没什么店铺,说5星有点勉强.不知道为什么卫生间没有电吹风', 1)

In [43]:
# 划分数据集
from torch.utils.data import random_split

train_len = int(0.9 * len(dataset))
valid_len = len(dataset) - train_len
trainset, validset = random_split(dataset, lengths=[train_len, valid_len])
len(trainset), len(validset)

(6988, 777)

In [13]:
for i in range(10):
    print(trainset[i])

('入住的是260元的迷你标准间。感觉比想象的要好很多，房间如果住一个人很合适的，洗手间很大，很干净。房间里床上用品质量很不错，整洁如新。房间窗户为玻璃幕墙，无法打开换气。这是距离大连火车站最近的酒店。前台服务态度很好，很热情，业务熟练。就是退房的时候，查房比较慢，人多的时候，要多等几分钟。总体感觉还是可以的，交通极为便利。', 1)
('由于到店时间为凌晨1:00多，因此,估计房间比我预定的要升一个档次，很宽敞。而且早上可以看到外面的景色及鸟的叫声。不过早上是被鸟叫的声音吵醒的……室内有保险柜，感觉没太大用处；有冰箱，比较实用……早餐不好吃，不知道是多少钱的标准……', 1)
('刚住了两个美丽华240的贵宾楼感觉有点贵160比较合适吃早餐最好早点去晚了就没了一层的“碘泉”还不错可以去泡泡据德州本地人说那的girl是当', 1)
('大约2年前住过一次,也许是新装修过的原因,这次去感觉比上次要好,房间感觉不错,服务也蛮好,酒店租车的价钱也算公道', 1)
('房间还算可以，但硬件设施偏差，服务水平也很一般。', 1)
('很有品位的酒店,服务也非常到位.尤其感慨的是:能把酒店的客房布置成乡村旅舍的格调,既淳朴,又不失现代生活的方便,这个要赞一个!另外,酒店贴心的服务也让人感到温馨。入住酒店时，已经过8点，还没有就餐，酒店有位男性服务员（不知道是否是领班）脸上只出现了少许的犹豫，马上答应马上安排，让我们一家人真的很感动。菜品也很有特色。离开酒店的时候，想不到还有细致服务的感受，停车场服务员一见我发动汽车，马上过来递上免费的停车票，告知待会出去交给外面的收费员。这种细致的服务，确实体现了这个酒店的管理理念。提一个建议，从环城高速进入酒店的指示牌能否换成醒目点的，晚上入住酒店的时候，为找路花了不少的时间。', 1)
('酒店周末都系学生情侣入住，噪音实在恐怖，发现很多学生在前台的价格系120元哦.环境，设施实在系太差了!不建议住', 0)
('性价比还是不错的,房间也很干净,周围也比较安静,唯一的缺点就是房间有点小,我住的大床房间', 1)
('网上讲的房间是24平米，实际没有那么大。另外房的空调也不是很凉快!', 1)
('酒店周边环境尚可,离火车站5公里左右,算远,房间空气不行,较旧.不推荐.', 0)

In [48]:
tokenizer = AutoTokenizer.from_pretrained("hfl/rbt3")
import torch

## 定义打包函数
def collate_func(batch):
    texts, labels = [],[]
    for item in batch:
        texts.append(item[0])
        labels.append(item[1])
    inputs = tokenizer(texts,max_length=128,padding="max_length",truncation=True, return_tensors="pt")
    inputs["labels"] = torch.tensor(labels)
    return inputs

In [49]:
# 创建DataLoader
from torch.utils.data import DataLoader

trainloader = DataLoader(trainset,batch_size=32,shuffle=True,collate_fn=collate_func) #shuffle为打乱
validloader = DataLoader(validset,batch_size=64,shuffle=False,collate_fn=collate_func)


## DataSet 只返回一条 DataLoader 返回一个batch

In [38]:
# trainloader[i] 是错误的
## 读取数据
next(enumerate(trainloader))

['第一次去郑州就入住的宾馆.去的时候打表被出租车司机黑了,后来知道了,到郑州打车可以讲价的,机场到中州皇冠90元足够了,如果是坎价高手估计80也能下来吧.有免费的游泳池很不错,但游泳池不太好找,而且去的路上要小心台阶,本人就不小心拌倒了,因为没有明示,这点酒店做的不到位.', '环境比较旧，但是床单、毛巾都比较干净，前台服务态度良好。', '交通很方便，离建国门地铁站步行5分钟，但是房间太小，感觉很老气的房子，进屋后觉得很压抑。房间内味道也不是很好。个人认为性价比差。', 'GOOD不错的酒店,还是好呀OK不错的', '总体来说不错。交通比较方便，早餐也可以。步行去沃尔玛购物约十分钟。去旅游的话还是开车方便，景点可以去多去几处。补充点评2008年4月13日：小心电梯夹人，合上的速度太快了，很少见。', '酒店的环境,房间和服务都不错,但是门口的保安就很差.让人联想到"打手".再加上网上也有对保安的说法,以前还不以为然,现在不得不同意他们的说法了.宾馆反馈2008年6月12日：尊敬的客人：您好！看完您的点评，酒店曾第一时间试图联系您了解事情的始末，但未能联系到，我们深感遗憾！同时，酒店立即以书面形式责成酒店外保所属的物业公司需加强对安保的培训和督导，并以该案例为戒，切实做好对客服务工作，避免类似事件的再次发生，否则酒店有权中止和物业的合作。如家始终秉承为每一位宾客提供安全、洁净、温馨的住店环境，也真诚的希望每一位住店客人能对酒店的工作进行督导和建议。我们感谢所有帮助酒店健康成长的客人！', '接站免费司机是四川人很实在,在路上告诉了一些初到拉萨的注意事项,宾馆很小,不是我们内地的星级标准.早餐还行,卫生间很大,就是价格稍高,我们到的第二天停电,所以我们换宾馆了.', '我订的是商务大床房，给我的房间是8418房，床是挺大的，但是房间太小了，基本上是进屋就上床了，连椅子都放不开，但是有个看不到海景的大阳台，不知道是怎么设计的，估计这房应该是个单人房改的。如家的电视节目有马赛克，给前台打电话，他们说叫工程师来看看，结果过了几分钟来了个拿对讲机的大婶，告诉我们是信号的原因，所有房间的节目都这样，要到晚上才能好，我们想那就算了，可是过会和我们同行来的另一个房间的朋友说他们的电视信号一直很好，气死了，如家竟然这样骗顾客，给前台打电话，又改口说是部分房间的信号是这样。晚上8点多的时候信号好了，但是第二天依然还是有马赛克，到了晚上也没好。住了三晚，拖鞋一直没给换，都破了。第三天蚊香片没给换。房间内的饮水机有很浓的84消毒水味，根本没法喝，自己到家乐福买的桶装水。只有一个床头灯，而且接触不良，不打它不亮。建议以后入住这家的顾客不要住这个带阳台的房间，没有阳台的房间还是很大的。补充点评2008年6月23日：忘了说了，地址位置还算不错，公交车挺多，出去玩的话先去看看公交车的路线吧，不过车开的也很慢，我们坐了一辆从石老人始发的车回如家，结果那车最高时速才40迈，一点不夸张。步行去八大关也很近，也可步行去二浴，就是它的大门不是对着香港西路，有时出租车会估计要几个圈子才开到（青岛的出租司机良心大大的坏了，宁可被全国人民骂也要坑那几块钱)', '要不是赶飞机，绝对不会入住这个酒店，一到前台就听到旁边的顾客和酒店人员在交涉，原来是他们放在大堂门口的私家车被撬了，车上的数码相机等东西被偷了，实在是太不可思议了！到房间之后本来想出去吃晚饭的，也不敢出去了，怕东西被人偷', '环境不错。不过离泰山还是有段距离。要是能包含早餐就好了。', '这是握住过的最便宜的五星级酒店，金陵酒店管理的，酒店的硬件很部错，卫生间的面盆与淋浴房的间隔有点小。', '和网上看到的点评是一样好！虽然到大同的时候，天气很冷，但是到了酒店会觉得很温暖！房间的环境很好，服务员也很到位。意外的是，房间里放了一张欢迎我们的信，这是以前所有宾馆没有遇到的！以后有机会再去，一定还会选择这家宾馆！', '环境优雅安静，湖景房确实美景如画，早晚在挂满了咏风叹景对联的长廊散步闲坐，身心极度放松。房价虽高，环境确非镇中酒店能比。在此小住，有傍湖泳池任游，有满目湖景，连游湖也省了。早餐也够水准。', '以前在学校读书的时候老板曾经带我们去过这里打保龄和吃饭等等，环境不错，房间也挺舒服，是闵行区比较高档的酒店', '总体来看，酒店价高，设施差，不值得推荐。价格338元标准间，在同类房价中偏高。设施差有以下几点：整个房间没有一张纸，一支笔。卫生间没有浴帘，洗澡后满地是水，地面打滑，水龙头出水很小。早餐7点才有，包双早等于空话一句。免费班车，只送2号航站楼，在强烈要求下才送到3号航站楼，如有误机还不负责，除非提前三个小时送，不合情理。', '早上八点多到酒店,预先订了房的,却被告知十二点', '入住时处于展会附近，到前台时被告知由于晚到1小时，定单取消了。追问是否还有房间，回答曰：“没有”（大概是生意太好，不想做携程生意）向携程反映，发现是信用卡担保定单-于是立刻有房间了。进入房间，发现没有打扫过，反映给前台，说立刻通知处理，结果等了40分钟，催了4次，发了火才有服务员来。房间不错，没有多余的无必要的设施，但外墙由于挂了竖幅，大风吹着猎猎作响，影响睡眠。还没完，早上专门买了餐券，到自助餐厅-什么都没剩下，稀饭都没有，难道两个人花30元，分食唯一的一片面包？还有其他人也在虎视耽耽。', '由于酒店距火车站近，所以出租车不愿去，但这是长沙出租车主管部门的问题，和酒店无关，后来火车站广场上一位交通协管员叫我们坐1路公交车，3站路就到了，只要1元钱，很方便又便宜。房间很干净，还免费送水果，下次有机会还住这个酒店。', '地理位置距离通常的客运码头比较远，要横穿小岛，预计30-40分钟，酒店处于岛的另一面很安静，游客不多，适合疗养，门前就有一个小码头，但每小时一般。', '我住的是特色标间，所谓特色，是有些类似家的感觉。寝具不是单调的白色，是条纹和大格子的，感觉很温馨。圈儿椅的靠垫是卡通的加菲猫头，明黄的颜色有点扎眼，和周围配在一起感觉有点不协调。客房硬件评价3.5分。加湿器、烫衣板、电熨斗、吹风机、小冰箱等俱全。缺点：液晶电视固定在墙上，位置不好。一是遮挡了一个电源插座；二是与桌子搭配不当。桌子（与冰箱柜一体）在电视下方，如果坐在桌子旁上网或工作学习，正好挡住了电视屏幕。错开坐，正好是冰箱柜，腿脚伸不开。', '我住的是豪华大床房，硬件不错，可惜床单上有细小毛发，不过服务台获知后马上就换了。自助餐很好。这是桐乡最好的酒店了。', '总体感觉不错.只是入住时收音机调节钮不能使用,打电话请工程部维修后才能听音乐,5颗星不应该这样.地灯也不亮,没有再计较.', '首先，服务员态度可以，有电梯，房间比较干净，床很大，下次还会住的，不过早餐比较差点', '环境很好，房间不错，网速还可以。早餐不太丰盛，很多都是辣的。选择也不多，看了一圈也没有什么想吃的。饭店离机场较近，饭店后面有超市，美食一条街。', '我们定的是特价大床房，很幸运，去了就免费升级成豪华大床房了。位于四楼，房间还算宽敞，而且很干净。我喜欢洗手间的玻璃屏风，这样显得整个房间比较大。不喜欢透明的话还可以放下卷帘。这儿的床很好。床旁边的台灯也漂亮。唯一毛病是淋浴房门无法合紧，洗澡的时候要拽着门，防止水溅出。好在只住一晚，这点小困难还可以克服。总的来讲，三百元就住到这样的旅馆，性价比已经非常好了。', '每次到福州都住这里，就是宾馆前台服务太慢了....', '总的感觉很不错,客房有22层左右,楼层很高可以看的更远,但是窗外没什么好看的,呵呵...服务嘛很好,随叫随到,我刚入住的时候就有服务员问我是不是要打扫房间,真的是很温馨,你需要什么服务客房部都会来帮你,不过有两点不行,首先就是电话费太贵了,1.7元每分钟,真的是太贵了,其次就是中央空调的问题,白天很好,制冷效果真的是很好很好,但是到了晚上特别是深夜居然会停了,害得我被热醒了,那个汗啊是真的多,所以希望酒店能考虑到每个客人的习惯问题不一样,如有从新启动或给空调加水,最好是选择中午的午饭时间或晚饭时间,人少的时候,晚上千万别关,因为每个人的睡眠习惯都不一样,一有不舒适就会醒的,所以希望能改正.', '首先应该讲携程的服务是非常到位的，为本人提供了不少方便。其次讲讲扬子岛酒店好的地方：1、位置真是好的没话讲，距解放碑步行只要两分钟不到，周边吃的、买的、看的都很多。2、服务员很热情，尤其是门童，这也是很多人肯定的。3、设施较全，大厅的马桶旁边都有垫纸（这一点应该是其他的很多做的不好的地方），当然与它的大厅在七楼应该也有很大关系。4、房价根据时间做调整，周一比周六便宜。重点讲讲不足：1、预订信息不准确。本来预订时说没有大床房，所以定了两个标间，但入住时又给了一个大床房，之前没有通知；2、大床房没有标准间大，而且相差很大；3、房间在刚进时有异味，虽然不太明显；4、烧开水的壶大多上盖损坏；5、卫生间没有吹风机，是另配的，我住的那间卫生间的插座有问题，吹风机只能在外面用，可是外面又没有镜子；6、下午五点多服务员就上门进行夜床服务，时间实在是太早了；7、保险箱有问题，按说明是无论如何用不了的，我和服务员按说明摆弄了半天都不能用，都已经报修时，突然又好了。8、水龙头只有一个，没有专用的饮水龙头。9、消防通道又偏又不干净。至于有的朋友所说电梯慢的问题，我个人感觉如果不坐观光电梯的话，速度还是可以的。而观景房实际上大多看不到什么景则是位置所限，周围都是高楼，没办法。', '作为一家经济型酒店，其最大的优势是地段，出门就是酒吧一条街、步行街，如果你想晚上去逛一下，走一下、玩一下的话，出门便是。标房有三种，推荐入住豪标，216元。但预定的时候最好要求大床房。否则可能给你一间带麻将桌的。不太方便的地方一个是酒店大门不太好找，第一次找了一圈才找到。而且进了大门，得先坐电梯至七楼才是总台。早餐一般，东西不是很多，而且是7－9点才有，结束的好像早了点。但对一家经济型酒店来说，总体感觉还行，对于216元的价格来说，还是比较超值的。', '号称三星，顶多招待所的标准，房间前面是个施工工地，晚上也在施工，很吵。还有这个迎宾员感觉有像索要小费的样子，不知道是不是', '10月25日入住单人大床间一晚,感觉较差:1.晚上22:30左右入住,前台接待很冷淡,无笑容,感觉不亲切;2.最可怕的是冲澡3分钟后淋浴龙头停水,2分钟以后浴缸龙头也完全停水.没办法浴室内打电话给大堂,说派人上来看一下,这时发现房间内未配浴袍.后大堂副理上来,告诉也有其它房间有类似情况,因最近酒店附近管理维修.只是建议给换房间', '入住感想如下、共大家参考:1、典型的国营招待所、除了有个很小的小卖部外什么都没有。2、房间设施陈旧、毫无住宾馆的感觉。3、谈不上服务、电视遥控器不管用、打电话给前台后、直至离店也未送来。4、浴室没有垫地的毛巾。建议后来的朋友、千万不要住这里。另外、希望携程应对酒店进行评比、不符合要求的店不要推荐、否则给客人造成不便。']
[1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0]

(0,
 {'input_ids': tensor([[ 101, 5018,  671,  ..., 4157, 6983,  102],
         [ 101, 4384, 1862,  ...,    0,    0,    0],
         [ 101,  769, 6858,  ...,    0,    0,    0],
         ...,
         [ 101, 1384, 4917,  ...,    0,    0,    0],
         [ 101, 8108, 3299,  ..., 3341,  117,  102],
         [ 101, 1057,  857,  ..., 2361, 3307,  102]]), 'token_type_ids': tensor([[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 1, 1, 1],
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 0, 0, 0],
         ...,
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 1, 1, 1],
         [1, 1, 1,  ..., 1, 1, 1]]), 'labels': tensor([1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 0, 0, 0])})

In [39]:
# 创建模型以及优化器
from torch.optim import Adam
model = AutoModelForSequenceClassification.from_pretrained("hfl/rbt3")

optimizer = Adam(model.parameters(), lr=2e-5)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at hfl/rbt3 and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [45]:
# 训练与验证

def evaluate():
    model.eval()
    acc_num = 0
    with torch.inference_mode():
        for batch in validloader:
            output = model(**batch)
            pred = torch.argmax(output.logits,dim=-1)
            acc_num += (pred.long() == batch["labels"].long()).float().sum()
    return acc_num / len(validset)


def train(epoch=3, log_step=100):
    global_step = 0
    for ep in range(epoch):
        model.train()
        for batch in trainloader:
            optimizer.zero_grad()
            output = model(**batch)
            output.loss.backward()
            optimizer.step()
            if global_step % log_step == 0:
                print(f"ep: {ep},global: {global_step},loss: {output.loss.item()}")
            global_step += 1
        acc = evaluate()
        print(f"ep: {ep},acc: {acc}")

In [46]:
## 模型训练
train()

['如果用一句话来点评：服务远远好过硬件。这次入住了行政湖景房和豪华商务房，感受比较多，就多说几句。入住当天虽然没有如约拿到双床房（可能入住人太多，说是还没有打扫好），但是前台安排了最高层的湖景房，补偿了一下。很少见的是每间房只提供单早，每次都要签单，稍微有点麻烦。不过早餐45一份，内容也挺丰富，还有小笼蒸的糕点，很喜欢。在酒店中餐厅消费可以打85折，价格很适中，即使人少也能提供包间，还不设最低消费，不错。离西湖确实比较近，慢慢散步十五分钟左右绝对可以达到。在湖景房或者17楼湖景餐厅还可以看到西湖喷泉、白堤，很享受。门童非常积极主动，除了热情招呼，还会主动询问是否需要拦出租车，知道我们要去机场，还告诉我们等车的位置以及可以在酒店大堂购买机场大巴的车票。客房服务很及时，需要什么东西都会尽快送到，打扫卫生迅速到令人吃惊，我们才一顿早餐的工夫，回来屋子已经收拾整齐。前台工作人员让我印象最深刻的是一名叫欣怡的姑娘，耐心、亲切，在我提出要定多一间房，想看看房后，她很快处理完自己手中的事陪我们前往，提供了很多有帮助的信息说到房间，这确实是唯一令我觉得与这间酒店很不太相称的地方。虽然我很欣赏客房设施的全面，免费提供的水果和饮料，卫生间里既有浴缸又有淋浴房的多种选择。但是，不得不说，设施实在是“太”陈旧了，旧的衣柜的门开闭都有吱吱嘎嘎的声响，还要往上提一提才能关严实。旧的马桶里的水阀的链子都是断的用绳子修补好的，结果还是一个劲儿的断，在我们自己维修过两次后，不得已求助客房服务，他们立刻通知工程部的维修人员，很快换上了新的带铁链的，接着即刻又有客房服务人员打扫干净，衔接的那么好，服务总是无可挑剔。中途加定的豪华客房据说是按照五星级标准装修的，不过装修的品位着实不怎么样，所以也不显得新到哪里去。（而且后来通过携程预定到的房比之前我们去看的房小了不少，也没有之前看到的组合沙发一块儿，不知道是不是因为通过携程预定会比直接在酒店预定少那么二三十块钱就缩水的缘故，想不明白，同是5-7层的豪华房，怎么大小，设备还有区别呢？）建议向皇冠假日酒店或者新开元酒店的设计风格学习学习。如果酒店能够重新装修一下，我想即使价格再高一点，我还是会选择马可波罗。宾馆反馈2008年8月9日：非常感谢您我们酒店中肯的点评。您加订的是商务豪华双床房，而您参观的是商务豪华大床房。由于房间格局的不同，商务豪华双床房内由带琴凳的单人沙发代替了组合沙发。同时我们酒店也在逐步对老楼层的设施设备做进一步的改进。您的建议对我们很重要，再次表示感谢！衷心期待您的再次光临！', '酒店的环境在安庆还算不错，不过有点老，早餐很好！', '住了不下七八次，是虹桥迎宾馆的老住户了。每次得到的服务说实话都很不错，有时还有免费升级，让人感到亲切舒心。但是这次入住，因为各种原因而颇为有些扫兴，希望酒店能考虑改进。1）可能是季节价格的原因，这次好像房价上升比较显著。后面又有公司的制定的规矩，所以只好预定最低的普通房。没想到普通房的设备比预想要差，比如书桌和电视不相对，淋浴要和浴缸在一起而不是单独的淋浴房，窗外景色较差。如果是这个价格住这样的酒店就稍感不值得。2）最后一天房间的空调坏了，把房间弄得像桑拿房（毫不夸张）。最后换了一个房间，却是比原来更差的双床房。想起以前经常能获得免费的升级，所以这次也就不特别计较了。只是稍稍失去自己长期以来对酒店的好感，很是可惜。宾馆反馈2008年4月9日：首先感谢您一直以来对我宾馆的支持和您中肯的意见。我们非常抱歉在您的入住期间，由于空调问题所给您带来的不愉快。其实对于老住客，我宾馆一直是给予特别的关注和安排的。对于您下次的到来，我们一定予以更进一步的关注。随着上海整体客源市场情况的变化，在全力提升我宾馆各项细节化服务的前提下，我宾馆的价格体系确有所调整。但是目前每周五、六、日还是有周末促销价格推出，尤其是行政房在推出优惠价格的情况下，仍予以宾客享受诸如：免费使用下午茶、根据宾馆入住率可延长退房时间至下午16：00、免费使用指定会议室两小时、入住首日赠送欢迎鲜花水果等一系列优惠政策。建议您可关心一下我宾馆推出的各类优惠促销活动，再根据自身的要求有针对性地选择性价比最高的产品。希望您能够一如既往地支持我宾馆，我们也将以更出色的服务来回报您。', '服务人员素质不高，屡屡出错！明明我为同事预留好的房间，居然不核对姓名就把房卡给了不认识的其他人了。如此低素质的错误！', '因行已打烊，身上已有人民了,但家店居然不能刷外卡,想先押美金,前台居然不同意,真的是....死人了,本要我押行李，真不知道押美金比押行李保障？能力有差的，另外在退房前台的服人度不佳,所有要我名的表都是用的,一貌都有,不遭的民生能和交通算方便就是了补充点评2008年7月10日：临Τ┬丁ず楞楞', '安亭路是很小的一条马路，酒店也算是闹中取静了，花园洋房非常有特色。', '不错的地方，房间不错，服务也可。除了火车声音有点受不了。', '服务实在太差!7月9日入住的,晚上11店打1168总机拜托第二天早上645分叫醒服务,房号:2319(便于查询与确认)。竟然没有做到!!这是我这个长期出差者第一次碰到的事情,因为10日早上830分有会议才提前一天住酒店的,还好这个酒店的床板硬得不能好好入睡,才"救"了我。特此评价。', '300多的价格入住这家佛山历史最悠久的酒店也真是值得，起码起到缅怀历史的作用，要知道它是广东第一家具有楼顶国产旋转餐厅的酒店。推荐这家酒店吃的地道，很具佛山本地特色，不管是二楼中餐还是楼顶的旋转餐厅用早茶、午饭、晚饭都可以，价格平民化，不像一些带个旋转就一定来个套餐。如果是初次来佛山，推荐入住这里。酒店服务设施难免老化，但是还过得去吧。房间10多平米，不大；附近就是佳宁娜听说那里的房间更加小；附件游览的地方是百花广场（商业广场），祖庙', 'т腹隔腹タ癸ǐ隔1-3だ牧诀初娩暗诀初ぺぃ25じRMB衡ス惠10だ牧逗ゑ耕Τ', '我还是比较喜欢德州的凯苑温泉度假村便宜148元安静不会有电话打扰温泉也很好只是在开发区里城里远了点', '由于延安路上在进行轨道交通的施工，所以交通情况不是很好，一开始叫车都不知道能不能在延安路上叫。刚进去感觉不是很好，有股味道，房间内也是。豪华标间没有介绍的30平米，有点小，布局还不错。工作人员还是蛮热情的。补充点评2008年8月13日：房间里面的床貌似不是非常干净，第一个晚上脚脖子那边就起了好多红块块，超级痒，这点让我有点后怕。', '硬件和软件均非常不错，下次去成都考虑入住。', '两间房只给两条毛巾，加一条毛巾要收费5元，太过份了吧？？？', '入住的时候我强调不要靠窗的房间，结果晚上休息的时候发现自己根本就是住在马路上。凌晨一点睡下，窗户外传来嘹亮的汽车喇叭声，而且连绵不绝，拉萨的司机在一点多也频繁按喇叭；在床上还可以听到大街上人高声说话的声音、楼下店铺关门的声音。天哪，噩梦啊！马上要求换房间，答应的比较快，原来还有其他的房间空着！他们把条件好的房间空着，却把客人安排在靠近马路的房间！实在可恶', '比较满意,酒店比较新,房间也比较大,感觉还可以', '前几日山西旅游到大同，通过电话定了这个酒店。总体感觉非常不爽。房间刚刚够上三星标准，偏偏报了一个四星；入住后感觉就是一个洗浴中心，房间不隔音也比较乱。第二天结帐又是内部结算又是房间内的物品损坏，上去一看又说查错了，真的不知道搞什么。下回请携程推荐时注意一下酒店品味。不要砸招牌。', '此酒店硬件设施非常差，比如：房间是KTV包房改的，被子很薄，早餐在简陋的包房里就餐（早餐太简单），服务员叼着烟往餐厅里送早餐，大堂只有一个男女公用的卫生间，里面还放着两辆自行车，等我到了酒店服务员还找不到我的订单等等。所有这些都是客观事实，并非我捏造。', '这是第三次点评，纯粹是为了拿积分。没什么可以多说了，服务不错。', '10月25日入住单人大床间一晚,感觉较差:1.晚上22:30左右入住,前台接待很冷淡,无笑容,感觉不亲切;2.最可怕的是冲澡3分钟后淋浴龙头停水,2分钟以后浴缸龙头也完全停水.没办法浴室内打电话给大堂,说派人上来看一下,这时发现房间内未配浴袍.后大堂副理上来,告诉也有其它房间有类似情况,因最近酒店附近管理维修.只是建议给换房间', '那是什么破酒店，你们携程也对外推荐啊，那里面那个破。服务极差，我入驻708，房间门是用纸胡的，洗脸盆下水坏了了。问服务员，酒店是10年前装修的，而携程介绍是2006年装修的。早餐质量极差，服务员的服务态度也很差，想要个汤勺都没有。吃到后面连盘子都没有。其实我感觉最差的是携程的服务，向一个钻石贵宾推荐了一个未经核实的虚假信息，然后启客户不顾，让客户自行在一个陌生的城市去寻找住处，到2008年1月1日仍没有对投诉进行反馈，不过我可以理解，因为携程处理该事务的人员放假了。至于客户有什么样的意见，哈哈，开假后再说。再见了携程。宾馆反馈2008年1月2日：感谢您对我酒店提出宝贵意见，对于您在我们酒店入住期间所经历的不满意，我们深表歉意，我们酒店是98年开始营业的，经营至今曾分期逐层进行装修过，而且以供客人多种房型选择而著称，像适合商务客人的特色标准间（以大床居多，06年新装），适合夫妻带孩子出行的家庭房，还有普通的大床等。关于餐饮方面，确属我们管理疏忽，不过时至春节，招工甚难，还望能多加理解，不过这不是理由，我们一定要加强培训，提高员工顾客意识，做为对你的致歉，我们将减免您的当日房费，并附赠您一份礼物以表歉意，期盼您再次光临指导！', '绝对的市中心位置,对面就是丁香莲,隔壁就是卖最好的湖笔的王一品总店.步行5分钟就是最热闹的红旗路,定的是豪华双人房,因为', '酒店设施还可以,服务也不错.值得一提的是:早餐不象是所谓的五星级的早餐.门童的服务也不到位!其他都还好!', '本人5月3日入住。设施太陈旧，一股霉味，住店还收停车费，强烈不推荐。另外，协程给出的地址有误，是浔阳路，不是浔阳东路。', '特别喜欢房间里的床，睡觉非常舒服。但酒店周围环境不好，特别是很难叫到车，足足等了1个多小时，耽误了不少时间。补充点评2007年11月9日：不喜欢酒店周围的环境,很乱很脏，但老外特别喜欢，据说有上海的特色吧。', '这次没有定行政间，想看看普通大床和行政房的区别。发现房间还是不错的。床很大。服务态度还不错，门口换了女门童，笑容不错。前台接待和礼宾部的服务也不错。', '交通便利，从酒店去大巴扎只要起步价就到了。房间也舒适，就是隔音不怎么好，隔壁声音听得见，正好碰上隔壁打牌，同前台打电话后，前台派人跟隔壁说了，就不吵了。总体不错。服务不错。', '不管是服务还是硬件都绝对够不上四星级，尽管前台确实挂着四星的牌子！！！依我看，就3星还不到。不过价格也步态四星级。', '位置非常接近浦展;然是二面路,但相,不有太多。服素一般,只是早餐相差,只有:吃或不吃', '酒店很新并且很有档次和气派，主楼设计和总体设备设施让人感觉非常不错，周遍是一个广场，视线很开阔。但令人非常愤怒的是，为什么通过携程网预订的客房总是常常被安排在不方正的――床和电视机等客房设施都歪歪扭扭摆放的房间（1710房），真的不止一个客人反映这样的问题，携程网的客人一样付钱消费，为什么会受到不公正的待遇？！难道就是因为那40元/间.晚的返佣费给的不甘心？！酒店在争创五星，应该做到给每一位客人提供最优质最满意的服务，否则受到伤害的顾客永不会再光顾，何况现在酒店这么多……望酒店领导能重视这个问题，解决这个尴尬的局面，真正让酒店在硬件和软件都上五星。', '酒店是新装修，劳动西路，离田汉大剧院很近，看表演方便', '酒店的服务不错，房间很干净。提出要上网后，就给换了个能上网的房间，上网费也没有收。交通方便，门口就是大连火车站。原本以为会很吵，可以住在17楼，根本就听不到声音。费用方面200多元，感到很值。']
[1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1]
ep: 0,global: 0,loss: 0.6491273045539856
['这是一家国营的宾馆，感觉一般般！设施比较陈旧！', '4月份回青岛顺便带朋友去玩的，为他们选择的就是该酒店，房间干净整洁，但是卫生间的设施太简陋，房间内有小冰箱，考虑的比较周到，如果卫生间设备好一点就更好了！服务人员的态度非常好，没有给我们青岛人丢脸，电话随叫随到。', '第一住的房都是味，地上有好香灰，后了另外一味那麽重！建酒店清生必注意，及最好有非吸', '仅住了一天，单人房，感觉还满意。服务不错，早餐不错，结账也很快。去不远的西关人家吃了顿晚饭，驴肉锅仔，便宜又实惠。房间稍小了一点，书桌上放了电脑稍显拥挤。', '房间还不错。床很舒服。但交通就不是非常好了。大堂容易把人走晕。很满意，下次还住。', '位置好,不错,挺干净舒服,价格也合适,去西安旅游推荐', '国际大酒店订不到房间，抱着试试的态度订了这家感觉还是很不错的，环境也不错尤其床和被子，真的很舒服，比国际的好得多唯一的缺点是地点有点偏', '房间挺大，设施也还好用，但装修很差，窗台部分墙壁的壁纸都脱落了，很难看。卫生间比较简陋，但各种用具都还能正常使用。', '还是不错的，交通也比较方便.总的来说还是可以的', '1.价格不公正，明明携程网上写的是￥200，结果住了一晚上第二天结帐时被告知￥390元，而且，预付订金的时候也没人告知价格，付订金时根本无人告知，只知道收钱，收钱时小姐把钱从客人手上抢过去。2.没有早餐，入住时携程写的双早，结果被告知早餐要￥10元/人。3.房内标明有桑拿足浴室，找了半天没有找到，问到前台（自己找下去）被告知桑拿足浴室根本没有设立好。4.卡拉OK室价格不公正，￥280元/场/人，和上海的歌城在黄金周的价格一样。5.酒店没有好路，一路上颠簸进去，结果车子费油不说，离合器还差一点挂掉，路上没有一个指路牌。6.奉劝广大住客，在和携程网确认价格之后，要再打电话去酒店确认价格，因为携程网上价格和酒店价格不同，相差甚元，不知携程如何更新他们的资料？', '装修的味道太重，商务标准间的房间太小。旺季的原因吧，我结帐的时候听到当天的房价又提价了，坐地起价，没办法。', '隔音太差，走廊有人说话就像在自己房间说话一样。房间门关闭不顺畅，要用力推。服务员爱理不理的，前台服务员连英语也不会说。卫生一般。', '这家酒店以前未觉得有什么，最近入住两次非常郁闷。第一次，我定了一天，第二天居然酒店前台经理说不能续住，第一次遇见，携程还帮酒店说话。今天住酒店没有空调，三星级酒店，不可想象，服务员的解决办法就是拿个电风扇给我，超搞笑。携程的工作人员说酒店没有空调没有说法也是正常的。我真不知道携程的佣金是不是拿的有点太轻松了。没有答复的话，抛开酒店不谈，我觉得我对携程信任度也大打折扣。了。', '该酒店地理位置较好，比较干净，可以上网，单间内竟然还提供电脑。在拉萨市来说比较难得！补充点评2007年10月30日：2楼的火锅城，味道不怎么样。火锅城演艺时间太长，影响休息。', '是我在北戴河附近住过的的比较舒适的饭店，是凯莱管理的，从服务到设施都比较正规。房间有点旧了，但还算整洁，水有点黄，建议多带点瓶装水饮用，环境不错。服务也不错，效率很高。让我比较满意的是餐厅，饭菜口味不错，而且不是很贵，还专门为小宝宝们准备了塑料的餐具，很周到。', '酒店位置不错，去哪里都方便，服务很好，前台MM漂亮热情，中餐厅美食节不错，确实是内蒙的羔羊和深山老鸡（我家乡就在内蒙-呼和浩特）。客房干净舒适，还可以免费上网（据说是10M光纤哟）。下次去重庆还会选择此酒店。性价比高！！！！！！！！！！！！！！', '在导航下容易找到;前台价格比携程贵20元;环境在城市中算很不错;服务态度等看出酒店员工受过培训,效果不错;总机用语,态度礼貌;门生有微笑,在新会这地方是天堂级服务;早餐(送)的环境,服务不错,只是欧陆式早餐份量较少,国人还是挑中国早餐比较满意.(当然,酒店价格在当地算是比较高.但至少一分钱一份货,值得.)', '前台服务挺热情的，周围交通也还方便。只是酒店卫生间相临的地毯潮湿，有点发霉。但是价格便宜，性价比还过得去。', '酒店占地面积很大，号称花园式。住的迎宾楼，条件很一般，还算干净。一楼，没有宽带，据说三、四楼才有。因为提前订好，到达时一看，要求加的床已经提前加好，还不错。考虑到是在安庆，房价也还便宜，一切都不计较了。', '房间很小，与行政间的名字不符。另外这家酒店的按摩可千万不能叫，超级黑！结帐时居然会有打手上来，请大家注意！决不会再入住此酒店。', '酒店最大的特色就是房间大。问题在于，我在前台明明刷了两天的预授权，但是服务员却只给我做了一天的房卡，我每个月都会至少住一次太平洋，每次至少3天，每次只做一天房卡的事情发生也不止一次了！！而且楼层电话是坏的，没办法打到前台区，每次都害得我跑到大堂去重做房卡，这样的服务是在是让人气愤！！', '太搞笑了！住了这么多次酒店宾馆都没有收停车费的，唯独东都宾馆收停车费，而且事先也不说明！！！当一个当兵的来收我停车费时，我破口大骂，先震他个四晕八素，然后趁他发懵时一鼓作气接着骂！声音还特大，一副要钱没有要命一条的架势，最后闹得收费的直犯晕，最后也没收费！这方法可供以后拄这家宾馆的人借鉴一下！（此方法切不可模仿，此次未交费纯属侥幸）至于其他的感想，和一经发表评论的人的观点一样，一个字：差！奉劝大家住店前三四而后行！', '交通位置很好,服务设施还可以.但价格有点高,可能太原的酒店价格普通比较高的原因吧!', '订的是豪华房，但是还真的挺小的。服务还可以，要求晚点退房同意的，酒店也有班车往返市中心。其实地理位置挺靠近铜锣湾地铁站的。就是后边的一片坟场，如果有忌讳就要注意了。', '绝对不值!!!刚住进去卫生间水管爆裂,,匆忙找服务员,半天才来,非常麻木,看了看去找修理工,大概5分钟后回来,此时房间积水有1厘米,半天没修好,要求换房间,然后漫长的', '我是5月8日到9日定的贵宾楼层高级间[含早],给我的感觉是:---地理位置极佳,就在金融街附近---房间非常大和非常舒适,包双早,才1000块多一点,非常合算---唯一不好的是大堂在装修,搞得有点失礼,其他的都很好总体来说是一家不错的酒店,够了4星级标准!', '客户反映此家酒店的服务和房间也就是2星级标准。尤其服务及人员素质都不尽人意，令人失望。但在网上却排在推荐第一位置，请你们要按照实际情况来向客人推荐。是一家很差的酒店。宾馆反馈2008年5月30日：我酒店一直非常重视携程网客人给我们的评价，对于客人提出的意见我们会及时的进行改正和完善。今天我们发现点评中有一位客人对我们的评价很差，于是及时联系了实际住宿客人潘先生，潘先生反映在酒店住宿期间对客房、服务都很满意，点评是其朋友填写的。华庭时尚商务酒店真诚欢迎各界朋友来我酒店入住，也希望潘先生的朋友有机会来亲身体验！我们将努力为您提供热情优质的服务。', '在看过携程的点评入住的，订的女士楼层，总的来说非常不错，大堂有点小，倒也无伤大雅，房间因为全是套房，稍稍显局促了些，但是床真的是灰常灰常的舒服，粉粉的床具让人一见就忍不住“投身”进去，洗手间也显得稍小些，但还不错。早餐倒算干净，但品种太少。以后到深圳还会选择并且会推荐朋友入住的！', '环境很不错，房间也较大，干净、整洁、舒适，性价比较高。checkin虽然排队较长，但也较快。酒店自助餐厅营业时间到晚11时，而不是前台说的到晚12点。我们差点没吃上饭。', '12月4日～7日我们一行7人住进了皇嘉，给我和同事感觉都不好，一房间没有暖气，而且换房间态度不好，房间换后还是没有暖气；二房间卫生间设施差，台盆龙头出水很小，洗澡淋浴区，下水不畅，设施陈旧，卫生间洗澡环境很冷；三早餐尚可。希望皇嘉应该重新装修，现在的房间设施和服务不符合4星级的标准和要求。', '一句话：床太硬！一个晚上都没大睡好。喜欢软床的提醒大家一句，要有心里准备哦', '海兴慕名而去！我的评价：地段差，服务一般般，硬件还可以！']
[1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0]
['房间', '新乡国家饭店入住纪实：1.入住第一个房间，电视关不上，一直开着。服务员建议换房间。2.换的房间空调不行，又换房。我们拿着行李跟着跑。3.换的第三间房是有烟房，我们问：有没有无烟房？服务员告诉我们：我把烟缸拿走就行了。哭笑不得！4.晚上去餐厅大厅就餐，点完餐后，服务员告知：最低消费35元\\人。我们不能理解，服务员告知：酒店的新规定。电话投诉后，来人讲：服务员是新来的不知道。', '该酒店给人的第一印象就是：不专业。缺乏培训、管理不严，抛出硬件不讲，管理上跟私人小旅馆不相上下。酒店的餐厅应该是外包的，所以下午三点我去问是否营业的时候，接待我的先生会躺在床上和我一问一答；明明开了两天的房、交了两天的押金，只过了一晚还是会来催你退房，以便她们打扫卫生；应该说从酒店的硬件上看，老板还是投了很多资的，为什么不能请一个专业点的人来管理呢？建议大家不要住，感觉实在太差，失望是必然的，气病是可能的。', '还不错,来过石狮这么多回,就这家有档次,客房特别舒适,价格合理,物有所值,菜很好吃,就店很热闹,我在旁边办事方便', '这个酒店值得推荐,地理位置真是好,中式庭院也很美.就是服务有待改进,住了两天没看到什么笑脸;因为手机充电器是英式插头无法充电,向前台借接线板,回答是没有,第一次在四星酒店听到这样的回答...总体来说硬件是不错的,设施或许不是很新,但是环境优势突出.', '酒店服务很好，床很舒服，也许是比较喜欢西餐的原因，个人比较喜欢万豪的早餐，交通方便，因为去香港两天都在下雨，显得尤为重要，楼下通太古广场和地铁，大半时间都在太古逛了，还顺便看了一场电影，从LG去地铁站坐地铁去尖沙咀和湾仔都只有一站，铜锣湾只有两站，以后再去还会考虑住这里', '酒店位置不错，距天府广场和春曦路走路大概25分钟、打车5分钟。房间、服务也不错，够三星水平。只是早餐过于简单。房间地毯、墙纸略显陈旧了。', '客人很满意,我们也推荐其他同事入住.性价比好.交通方便,离火车站就5分钟路程', '环境和设施都不好,提前预订的不靠铁轨的房间没给保留,整晚的火车汽笛声影响了睡眠', '位置不错，上海徐家汇中心地带，性价比一般，房间比较大', '昨日再次入住五洲,总体感觉很好,各方面服务都很到位,特别是客房服务员的拾金不昧精神让我印象最为深刻,下次到石狮出差,依然会首选五洲.', '订的一般标准间￥228的，在前台等了十来分钟开好了房间，刚进了房间就被告知开错了，说开成了￥228的（其实就比￥228的多两瓶水，两小袋饼干），紧接着就被服务员赶（是赶，没错）出了房间，问新开的房间呢，服务员一脸的不快，说在开等会送来，又过了十来分钟服务员才又拿了房卡，房间设施吧感觉一般，达不到三星的标准吧，不及我在观音桥住得一些商务酒店，价格还能便宜一些。', '房间还不错，够大，不过床头有部分发霉的迹象，218元的价格还是太贵', '总算可以免费上网了～经过3年的营运，价格在不断攀升，硬件多少在退化，服务还是一如既往。呵呵，从性价比角度看有待商榷喽......补充点评2007年12月17日：房间内的温度是可以调节的，冬季里一般我都建议服务员给锁定在24度自动控制状态，没有那么干燥，感觉很舒服。', '差，太差了，希望不要推荐给携程用户。。。。。。。。。。。。免费注册网站导航宾馆索引服务说明关于携程诚聘英才代理合作广告业务联系我们Copyright1999-2008,ctrip.com.allrightsreserved.', '不错的酒店,去九华山很方便,比在山上动不动就5,6百的房间好多了.', '相当不错宽带速度很不错。周边环境也可以个人比较喜欢', '东楼挂2星或准3星合适.房间内卫生间设施差,且面积太小,卫生尚可.饭菜价格能接受,用餐环境好.饭店周边环境好.住店客人可免费游僧冠峰,魁星楼也不过几分钟的路.', '记得，一定要拔掉电话线，那些争取按摩业绩的小姐很有毅力，很晚都会打电话开发可能性，别以为已经打过就不会再被骚扰。', '与其他如家比，这家隔音效果出奇差，不知道是不是我房间的问题，隔壁的说话声，电视声，厕所冲水声，床上的嘿哟嘿哟声都能听到；另外退房时说房间毛巾脏了，要赔15元，买一条毛巾也就5元，怎么要赔15元？毛巾脏了就要赔，那以后谁还敢用你家毛巾？如家住了五六家店，感觉这是最差的一家。', '实在忍无可忍。1、水。缺水现象――洗澡至中途，突然断水，望着满身的肥皂泡欲哭无泪；多水现象――有幸目睹了水漫金山的壮观景象。我们住在2楼，半夜，只听到哗哗的水声，之后从房顶上渗出的水，蔓延了整个房间，我们淌着水冲进房间，只见被子已全部湿透，庆幸的是放行李的地方还未受灾，赶紧进行抢救行动。2、安全。大概山上已经提早进入了共产主义社会，客房有门等于没门，服务员可以拿着房卡随意进入任何已经入住客人的客房。半夜，我们已经入睡，可是突然有人开门进来，当我惊醒但还处于迷茫状态的时候，只见服务员在我的房间内若无其事的巡视。我感到自己的人身安全受到了严重的威胁。就这样被折腾了一夜，一宿未睡啊！现在是头昏脑涨、鼻涕一把、心有余悸阿！总结，千万别住在这样的度假村内了，黑店阿。', '关于1元的保险费，钱虽少但你应该事先告知，哪有强买强卖的，因为赶时间所以就没计较，有时间一点好好理论一下。', '看了前面介绍的推荐去入住的，结果很失望，酒店的淋浴居然没有维护设施，洗个澡弄得整个洗手间都淋湿了，小心翼翼的穿上已经湿透的纸拖鞋，还要担心摔倒，另外酒店的隔音设施非常差，走廊里一有人经过，你就别想着能听不见，我注的那个房间的电视还要搞笑，就收不来几个台，好不容易收到的台还全都是雪花，反正以后再也不去住了，唯一值得表扬的是服务员态度还不错', '服务值得褒奖，是见过的国营酒店里最好的，尤其是行政楼层长兴阁，贴心的服务，精致的点心，无线上网，免费的下午茶，感觉很惬意，尤其是服务员的素质，蔡雪妹妹的微笑实在让人难忘。大堂吧也不错。行政楼层1030一晚，含免费下午茶（长兴阁），每天免费洗烫4件衣服，免费享用4瓶小冰箱饮料，含早餐。性价比相当不错。好话说了这么多，批评一下：主楼和世纪楼的中餐厅真的很烂，据说是外包的，生意非常火，每天都是婚宴，要吃饭必须定位，否则排队吓死人。住了一个星期，两个中餐厅分别等到机会吃了一把，差点没被气晕过去。素质和环境和酒店本身相差太远，吵闹，难吃，奇贵无比，拿着红酒杯倒啤酒，拿着洋酒杯到红酒，厉害！服务员素质也不到位，和外面马路餐厅相当。酒店里两家中餐厅外包，天上人间也总会外包，都极差。日本料理店东西不新鲜，早餐每天都一样，只有鸡肉粥换成鱼片粥，呵呵，吃顿早饭吗，不用那么挑剔，也罢。4楼健身不错，很全，保健按摩很专业。总体来说，性价比不错，切记只选酒店自有的服务，准没错，外包的别再尝试了，只会影响心情。', '住中天也不是一次两次了，觉得不错才继续住的，这次回国在重庆转机，而且离车站又近，又是购物中心，所以这次仍然又选择住在中天，但是这次发生了件超不爽的事情，当天下午到达中天后，我们就去吃东西了，当天，重庆下着雨，天气变凉，就打开旅行箱加了件衣服，因为想到说一会儿就回来了，旅行箱就没有锁起来，结果等回到酒店后，酒店内已经有人来过了（出去的时候门是锁好的哦），而且里面添加了两瓶水（应该是服务生进来的），结果再看旅行箱，电话记事本竖着放在旅行箱拉口处，东西翻得乱七八糟的，倒还好，我给爸妈从美国带的保健品--老人服用的善存带的五瓶却少了一瓶，钱倒没有多少，200左右，但是超不爽的~建议酒店，下次在客人进住安排服务生把所有的东西都弄好，不要在客人入住后外出的情况下，让服务生单独进入房间，发生这样的事情对谁都不好，钱倒是小事，但是都从美国带回重庆了，结果就这样不见了，特郁闷~~~~~当然酒店其它方面还是不错的，下次还会选择入住，但是就是记得带把锁~~', '房间那是相当的差，不过也是挺便宜的。交通不太方便。建议不要选。免费注册网站导航宾馆索引服务说明关于携程诚聘英才代理合作广告业务联系我们Copyright1999-2008,ctrip.com.allrightsreserved.', '当地最好的酒店！但是五星级酒店不是地方标准，所以在硬件一般的情况下，还得在服务上狠下功夫，向优秀的五星级饭店看齐。', '五星级的酒店，三星级的房间，两星级的服务，零星级的环境。以后再也不会来这家酒店了。', '房间、卫生间都挺大，我们住的是大床房，床也很大，很干净，朝绿洲的这边可以看见东方绿洲的风景，除了酒店就可以直接进东方绿洲玩。但是酒店除了按摩外，没有其他娱乐设施。早餐品种不多，而且九点钟就结束了，没法睡懒觉。总体感觉还不错', '非常好，特别是休闲房。早餐非常丰富。再来还住。', '房间太小,设计不合理,竟然连会客小台桌都没有,我住的房间马桶冲水不畅,卫生间太小,洗裕区域和马桶区域太过狭窄,很不方便,总体来说,说它是四星级是太言过其实了,2星差不多.', '酒店比较老，但是房间还好。酒店虽不在市中心，但离我出差的公司较近，所以住过几次。']
[0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1]
['酒店很一般。根本就到不了3星。无论从硬件到管理，简直侮辱了三星的标准。房间潮湿味道很大，地毯，房间面积等等简直没有一件能让人舒心。我入住的是288的房间，也真佩服宾馆的管理人员，这个价格他们也敢要，我觉得180元以内还凑合。总之，不推荐大家入住！', '整体环境不错,离市区较远，出租车到火车站15快。我住南楼，298的价位跟房间环境比算贵。结账遇到很大麻烦，先说我用了付费饮料及食品。后来又说浴袍没了。通常大家住店都不会检查其是否存在。尤其是在四星酒店。', '很不错的感觉，不过只住了一天。很有品位。', '服务好。环境安静、位于国贸商业区，交通方便。就是房间内有点暗。不过相对于价格，还是瑕不掩瑜。', '房子还凑合，但是硬件不行，不象4星酒店，服务还可以', '装修典雅，服务到位！在当地已经算很好的了，吃的有点辣！', '服务员有礼貌,价钱超值.房间很大,不错,洗手间也很大.唯一隔音不是太好,而且附近食店不多.(但很多地方坐的士10~20元可到)*我住豪华房', '经常出差重庆，酒店都是公司预订好的，这次临时决定过去，就让那儿的朋友帮忙推荐。原本觉得随便找个有床睡的地方就好，对于服务、环境各方面没有任何的奢求。太意外了，君临给了我一个surprise。我是晚上到酒店的，还没有吃过晚饭，办好入住手续后，Waiter引导我到房间的时候和我拉家常，介绍酒店及附近怎么吃饭，介绍附近的交通，介绍如何在酒店里更好的享受生活……以往最让我郁闷的是住酒店经常网络不通，非得打几个电话和前台解释一通才能解决。但这次我进了房间，Waiter帮我连接电脑，确定网络可用后方才离开……太意外了，君临的细节、服务令我折服，国内我一直很推崇海尔所倡导的服务，但也只是平时媒体上看到的，移动的服务也很好，但我一般很少有空去对他们即时提供的服务作出简短的评价。此次却抽空做君临的评价，一是希望和我一样经常出差的朋友能有幸入住这样的酒店，感受宾至如归的感觉，享受生活；二是希望携程在各地多找些这样的酒店，让我们这些“飞人”有些归宿感；同时，也祝愿君临这样的酒店开得越来越好！', '这次住的是B座，价格同A座比起来也不算太贵，但是卫生条件，房间设施都很好。而且被子是我睡过的最舒服的', '我订的是祥和楼,房间和设施都很陈旧,看了房之后给携程打电话换成了泰和楼.房间还不错,是新装修的.美中不足是早餐时间太早,9点多就没了,没吃到.值得一提的是该酒店不时会有一些促销活动,比如我们当时订的是三间房,而酒店当时买三送一,也就是说订三间免费送一间,人多的话挺合适的,订房时问一问前台（订房时携程没说）,可以同时享受携程价格的．', '隔香格里拉很近，很方便，不过我门一般是去香格里拉，那次没房了才去的，感觉好算可以', '这个宾馆最大的特色就是房费里含了一日三餐，虽然我这次晚到早走，只吃了一顿早饭。房间在当地算是不错的了。希望下次能吃到他们的免费午餐和晚餐。', '其实不错啦，可能我住的酒店也比较少，至少在我住的酒店当中这个是不错的，可惜的是电视机实在是太大了。。。如果资金充裕可以考虑换背投的。。。还有房间的地毯可以换的颜色比较好点的。。。服务还是很不错的！！！这点肯定宾馆反馈2008年5月15日：感谢您的光临和点评,我们会认真考虑设备设施的改造问题.', '房间非常好，早餐还好，比较满意。房间缺少针线包，客房部人员反应速度比较快，再去沈阳还住高登。', '湖光山色几乎可以用完美来形容，客房是实实在在的江南木结构民居，非常干净，环境保护得非常好，员工也非常礼貌、服务不错，特别大的停车场，非常适合自驾游的朋友，其实酒店就在景区内，不过去景区需要买票。', '酒店内部装修，房间不错。不过其他的配套服务略差，没有收费的机场接送车，只能帮忙定出租，大门不在马路上，打车不方便', '入住大连富丽华东楼，新装修的，比西楼条件好，以后还会选择！', '临街的房间，特别的吵，晚上几乎无法睡觉。房间隔音不好，白天听到隔壁“嘿咻”的声音，晚上听到隔壁打呼噜，让人无法睡觉。', '跟同一条街不远的经济型酒店比较我更喜欢假日之星酒店我订的是商务大床房相比房间面积大一点感觉不那么狭窄还有浴室提供吹风机另家经济型酒店同类房间里也没有缺点：大部分经济型酒店不提供早餐还有就是房间的隔音效果做的不是很好神经衰弱的不建议入住', '地段还不错，但作为一家4星级宾馆，设施方面实在是不敢恭维。主要问题在卫生间。我住的是标间，可能其它房间会好一点。卫生间实在是太小了，打开门在里面转个身都困难，从来没看到过这么小的卫生间。其它地方倒也还好。但就这一点，我想我以后是不会去住了。当然好的地方也是有的，自助餐还不错，内容比较丰富，味道也不错，特别是那个什么虾。', '帮同事订过很多次，酒店位置很好，很方便。房间也不错。', '除了前台服务态度一般，基本不会微笑，其他情况良好。房间干净，周围有苏果超市，交通也算可以。卫生间感觉太小了。', '环境和房间设施都很舒适，服务也不错，经常还去一楼的西村喝温的清酒，刺身也是非常的新鲜，据说都是大连和日本直运过来的。', '我和朋友入住的是三居标准家庭套房,黄金周入住740元,我认为很值得,现在平时只要400多,我推荐大家如果人多可入住这家酒店的三居家庭房!!.', '酒店位置在交通十字路口，服务员一问三不知！该酒店原名叫什么华夏酒店，估计为了吸引顾客，起了个洋名成了“雷梦得。。。。。”，不必住此店了！', '我住的是大床房，房间很小，小到放不下太多行李。不过离地铁站的距离很近，但是由于崇文门地铁最近在大修封站了，所以地理上的优势基本体现不出来，路面交通比较拥堵，很不方便。酒店的服务也不是很好，早餐不能挂帐只能买早餐券，早餐券只卖当天的，要是想第二天早上省事，只能早起去前台买。洗手间很小；房间也打扫的不干净。虽然价格不贵，但是和同价位的如家、桔子比起来差太远了，以后不会再去住了。', '我是自己开车去的酒店，这个酒店如果是晚上入住根本看不到酒店入口处，我费尽周折边打电话咨询酒店边让车上的人仔细辨认，结果还是绕错很多地方好不容易才开到酒店大门口，那天正好下小雨，门口保安只有一人跑来，我在酒店门口依然看不到车库入口，要求保安带路，于是他安排一个管理车库的工人引路，那工人带我们到车库后一听说我们是入住客人不能向他交停车费，他立刻一溜烟不见人影，害得我们找电梯口回酒店找了半天！！！这种情况也许以前很难体现出来也许平时也不觉得怎样过分，但这几件事集中起来就反映了该酒店的管理薄弱的一方面，最重要的是我觉得作为一个好评如潮的酒店更不应该了！当然事后当晚值班经理的及时道歉和升级房间等等补偿行为也体现了该酒店管理层对客人的重视，体现了酒店有错及时改进的诚恳态度！而且第二天还通过携程要向我电话道歉！我也确实感到该酒店能有如此态度很难能可贵了！本来我不想点评此次事情，但后来觉得也不妨通过我的客观褒贬让大家看到该酒店的真实品质！也许我下次还会考虑入住该酒店，只是仍然希望酒店今后多积极发现不足，免得以后入住该酒店的客人那么麻烦同时也影响自己的声誉！', '住过几次，整体来说条件不错，性价比蛮高的一家哦！可能是入住率太高吧，常常是等打扫的时间比较长', '硬,服人切,但地略偏,美中不足.短期停留可湛江地首.然五星酒店水尚有些微差距,但整已具此血,景可期.', '酒店环境、服务、房间都非常不错，酒店的地理位置非常好，是闹市，走几步路就是著名的1912酒吧区了。CTRIP的价格也比较有优势，下次去南京还会选这家的。', '太差,根本达不到5星标准,房间旧装修很久的了,桌子都是坏的,唯一的是宾馆里的环境还可以,标准间里就太糟糕了免费注册网站导航宾馆索引服务说明关于携程诚聘英才代理合作广告业务联系我们Copyright1999-2008,ctrip.com.allrightsreserved.', '离景区近,住紫楼,房间一般,浴缸很干净,白天玩累了,泡澡很舒服,早餐太差']
[0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1]

KeyboardInterrupt:

In [50]:
# 轻量验证：单步前向 + 一次评估
batch = next(iter(trainloader))
output = model(**batch)
print("loss:", float(output.loss.detach()))
print("eval acc:", float(evaluate()))

loss: 0.40068623423576355
eval acc: 0.8301158547401428

In [59]:
# Step9 模型预测
id2_label = {0:"差评!",1:"好评!"}
sen = "我觉得这家店很好吃"
with torch.inference_mode():
    inputs=tokenizer(sen, return_tensors="pt")
    inputs = {k:v for k,v in inputs.items()}
    model = model.to("cpu")
    logits = model(**inputs).logits
    pred = torch.argmax(logits, dim=-1)
    print(f"输入{sen}\n模型预测结果:{id2_label.get(pred.item())}")

输入我觉得这家店很好吃
模型预测结果:好评!